import { writeFileSync, rmSync } from "node:fs";
import { join, relative } from "node:path";
import { runInSandbox, makeSandboxDir, copyCandidate, packageRoot } from "../sandbox.ts";
import type { OracleBackend, OracleVerdict, OracleTarget } from "../types.ts";
import type { Rule } from "../../types.ts";

// Tier 2 — the REFERENCE oracle: run the candidate against a known-correct
// reference (or a recorded golden I/O table) on the same inputs; RED if outputs
// diverge, GREEN if they match. This grades "is this the SAME AS correct" —
// off-by-one, wrong rounding mode, a reimplementation right on the happy path and
// wrong on an edge — the long tail of "looks right, computes wrong" where static
// rules are weakest (`wrong-constant`, unit/scaling bugs, serialization mismatches).
//
// v0.9.1 ships the GOLDEN-I/O flavor first: a recorded input→output table travels
// WITH the rule (versioned, reproducible), and only the CANDIDATE executes — no
// reference *code* runs, which keeps the trust surface minimal. The candidate runs
// in the context-scaled sandbox (light isolate locally; hardened container on
// ingest, which refuses rather than falls back). A live-reference flavor is a
// follow-up.
//
// Honesty guard: the golden table is VETTED and owned — a contributor supplies
// candidate code and *claimed* behavior, never the oracle of truth itself.
//
// Rule binding (check.kind: "differential-io"):
//   params: {
//     entryFile: "lamports.ts",     // candidate file to import (relative to fixture dir)
//     export:    "solToLamports",   // the function under test
//     cases: [ { input: [1], output: 1000000000 }, … ]  // the golden table
//   }

interface DiffParams {
  entryFile?: string;
  export?: string;
  cases?: Array<{ input: unknown[]; output: unknown }>;
  /** Optional wall-clock budget for the candidate run (default 30s). */
  timeoutMs?: number;
}

function supports(rule: Rule): boolean {
  if (rule.check?.kind !== "differential-io") return false;
  const p = (rule.check?.params ?? {}) as DiffParams;
  return Array.isArray(p.cases) && p.cases.length > 0 && !!p.export;
}

// A self-contained ESM harness: import the candidate, run each golden case, and
// exit 0 (all match → GREEN), 1 (any divergence → RED), or 2 (harness error →
// UNKNOWN). Deterministic; deep-equal via stable JSON.
function renderHarness(entryImport: string, exportName: string, cases: DiffParams["cases"]): string {
  return `// GENERATED by @brainblast/core differential oracle. Runs ONLY the candidate.
import { ${exportName} as fn } from ${JSON.stringify(entryImport)};

const cases = ${JSON.stringify(cases)};
function norm(v) { return JSON.stringify(v); }

let diverged = 0;
for (let i = 0; i < cases.length; i++) {
  const c = cases[i];
  let got;
  try {
    got = await fn(...c.input);
  } catch (e) {
    console.error("HARNESS_ERROR case " + i + ": threw " + (e && e.message));
    process.exit(2);
  }
  if (norm(got) !== norm(c.output)) {
    diverged++;
    console.log("DIVERGE case " + i + ": input=" + norm(c.input) + " expected=" + norm(c.output) + " got=" + norm(got));
  }
}
if (diverged > 0) { console.log("DIFFERENTIAL: " + diverged + "/" + cases.length + " diverged"); process.exit(1); }
console.log("DIFFERENTIAL: all " + cases.length + " match");
process.exit(0);
`;
}

export const differentialBackend: OracleBackend = {
  method: "differential",
  tier: 2,
  supports,
  async verify({ dir, rule, context = "local" }: OracleTarget): Promise<OracleVerdict> {
    const t0 = Date.now();
    const p = (rule.check?.params ?? {}) as DiffParams;
    if (!supports(rule)) {
      return unknown("rule is missing differential-io params (export + cases[])", t0);
    }
    // context "ingest" runs a CONTRIBUTOR's code on our infra, which demands the
    // hardened container. Executing a tsx harness in that container needs the
    // candidate's native deps resolvable inside it (esbuild/tree-sitter, musl vs
    // glibc) — a portable hardened-harness that is a tracked follow-on, not part of
    // v0.9.2. Until it lands we REFUSE (never fall back to light isolation). The
    // differential oracle is fully functional under context "local".
    if (context === "ingest") {
      return unknown(
        "Tier-2 execution on the ingest path requires the hardened-sandbox harness " +
          '(follow-on); refusing rather than running contributor code under weaker ' +
          'isolation. Proven instead under context "local".',
        t0,
      );
    }
    const entryFile = p.entryFile ?? defaultEntry(dir);
    const sandbox = makeSandboxDir(".oracle-diff-");
    try {
      const copied = copyCandidate(dir, sandbox);
      if (copied.length === 0) return unknown(`no candidate files under ${dir}`, t0);

      const entryImport = "./" + entryFile.replace(/\.(ts|tsx|mts|cts|js|mjs|cjs)$/, "");
      const harnessPath = join(sandbox, "_diff_harness.mts");
      writeFileSync(harnessPath, renderHarness(entryImport, p.export!, p.cases));

      // tsx imports the .ts candidate directly; no build step. Runs IN the sandbox.
      const res = runInSandbox({
        dir: sandbox,
        command: "npx",
        args: ["tsx", relative(sandbox, harnessPath)],
        context,
        timeoutMs: p.timeoutMs ?? 30_000,
        readonlyMounts: [join(packageRoot(), "node_modules")],
      });

      if (res.status === "refused") {
        return { color: "UNKNOWN", method: "differential", detail: res.detail ?? "ingest sandbox refused", durationMs: Date.now() - t0 };
      }
      if (res.status !== "ok") {
        return { color: "UNKNOWN", method: "differential", detail: `candidate did not run cleanly (${res.status}): ${res.detail ?? res.stderr.split("\n")[0]}`, durationMs: Date.now() - t0 };
      }
      // exit 0 = matches golden (GREEN); 1 = diverged (RED); else UNKNOWN.
      if (res.exitCode === 0) {
        return { color: "GREEN", method: "differential", detail: `matches the golden I/O table (${p.cases!.length} case(s)).`, evidence: { cases: p.cases!.length, isolation: res.isolation }, durationMs: Date.now() - t0 };
      }
      if (res.exitCode === 1) {
        const firstDiverge = res.stdout.split("\n").find((l) => l.startsWith("DIVERGE")) ?? "output diverges from the golden table";
        return { color: "RED", method: "differential", detail: `diverges from the golden I/O table — ${firstDiverge}`, evidence: { cases: p.cases!.length, isolation: res.isolation, diff: firstDiverge }, durationMs: Date.now() - t0 };
      }
      return { color: "UNKNOWN", method: "differential", detail: `harness error: ${res.stderr.split("\n").find((l) => l.includes("HARNESS_ERROR")) ?? res.stderr.split("\n")[0]}`, durationMs: Date.now() - t0 };
    } catch (e: any) {
      return unknown(`differential oracle could not run: ${e?.message ?? String(e)}`, t0);
    } finally {
      rmSync(sandbox, { recursive: true, force: true });
    }
  },
};

function defaultEntry(_dir: string): string {
  // When entryFile is omitted the harness import would be ambiguous; default to
  // the conventional single-file fixture name.
  return "index.ts";
}

function unknown(detail: string, t0: number): OracleVerdict {
  return { color: "UNKNOWN", method: "differential", detail, durationMs: Date.now() - t0 };
}
