import { writeFileSync, rmSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { ts } from "ts-morph";
import { runInSandbox, makeSandboxDir, copyCandidate } from "../sandbox.ts";
import type { OracleBackend, OracleVerdict, OracleTarget } from "../types.ts";
import type { Rule } from "../../types.ts";

// Tier 2 — the REFERENCE oracle: run the candidate against a recorded golden I/O
// table on the same inputs; RED if outputs diverge, GREEN if they match. This
// grades "is this the SAME AS correct" — off-by-one, wrong rounding, a wrong
// constant — the long tail of "looks right, computes wrong" where static rules are
// weakest (`wrong-constant`, scaling/serialization bugs).
//
// HOW IT RUNS IN A SANDBOX, PORTABLY (v0.9.2): the candidate is TypeScript, but we
// must NOT need a TS runtime (tsx/esbuild) or any node_modules INSIDE the sandbox —
// native binaries can't cross darwin↔linux / musl↔glibc, which is what broke the
// first container attempt. So we transpile the candidate + harness TS → plain
// CommonJS JS ON THE HOST (using the TypeScript compiler we already bundle via
// ts-morph — compilation, never execution), then run plain `node harness.cjs`. A
// golden-I/O candidate is pure logic with no runtime deps, so node alone suffices.
// The result: the LOCAL light isolate and the INGEST hardened container run the
// IDENTICAL command (`node harness.cjs`) — only the isolation differs — so the
// whole harness/exit-code path is locally testable and the container "just works"
// (node:22-alpine ships node; nothing else is needed).
//
// Honesty guard: the golden table is VETTED and owned — a contributor supplies
// candidate code and *claimed* behavior, never the oracle of truth itself.
//
// Rule binding (check.kind: "differential-io"):
//   params: {
//     entryFile: "lamports.ts",     // candidate file to import (relative to fixture dir)
//     export:    "solToLamports",   // the function under test
//     cases: [ { input: [1], output: 1000000000 }, … ]  // the golden table
//   }

type DiffLang = "typescript" | "javascript" | "python";

interface DiffParams {
  /** Source language of the candidate (default "typescript"). Move 3: multi-language. */
  lang?: DiffLang;
  entryFile?: string;
  export?: string;
  cases?: Array<{ input: unknown[]; output: unknown }>;
  /** Optional wall-clock budget for the candidate run (default 30s). */
  timeoutMs?: number;
}

const JS_IDENTIFIER = /^[A-Za-z_$][\w$]*$/;
const TS_EXT = /\.(ts|tsx|mts|cts)$/;

function supports(rule: Rule): boolean {
  if (rule.check?.kind !== "differential-io") return false;
  const p = (rule.check?.params ?? {}) as DiffParams;
  const lang = p.lang ?? "typescript";
  if (!(lang in RUNNERS)) return false;
  return Array.isArray(p.cases) && p.cases.length > 0 && !!p.export && JS_IDENTIFIER.test(p.export);
}

// Transpile a single TS source to CommonJS JS (type-strip + ESM→CJS). No type
// check, no bundling, no native deps — pure string→string.
function transpileToCjs(src: string): string {
  return ts.transpileModule(src, {
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2022,
      esModuleInterop: true,
      removeComments: false,
    },
  }).outputText;
}

// ── Language runners (Move 3) ─────────────────────────────────────────────────
//
// The golden-I/O differential is language-AGNOSTIC in concept: run a function on
// recorded inputs, compare outputs, exit 0 (all match → GREEN) / 1 (diverge →
// RED) / 2 (harness error → UNKNOWN). Only the "get the candidate runnable +
// render a harness in that language" step differs. Each LangRunner encapsulates
// exactly that; the verify() body and the exit-code contract are shared.
//
// The exit-code contract is IDENTICAL across languages, so LOCAL (light isolate)
// and INGEST (hardened container) run the same command per language — only the
// isolation differs, and every language's harness path is locally testable.
interface LangRunner {
  /** Which candidate files to copy into the sandbox. */
  ext: RegExp;
  /** Prepare the sandbox (e.g. transpile) and return the entry spec the harness loads. */
  prepare(sandbox: string, copied: string[], entryFile: string): string;
  harnessFile: string;
  renderHarness(entrySpec: string, exportName: string, cases: DiffParams["cases"]): string;
  command: string;
  /** Pre-pulled hardened-container image (must ship the interpreter, nothing else). */
  image: string;
  defaultEntry: string;
}

// A self-contained CommonJS harness: require the candidate, run each golden case.
// Deep-equal via stable JSON. Plain node — no deps.
function renderNodeHarness(entryRequire: string, exportName: string, cases: DiffParams["cases"]): string {
  return `"use strict";
// GENERATED by @brainblast/core differential oracle. Runs ONLY the candidate.
const mod = require(${JSON.stringify(entryRequire)});
const fn = mod[${JSON.stringify(exportName)}] || (mod.default && mod.default[${JSON.stringify(exportName)}]) || mod.default;
const cases = ${JSON.stringify(cases)};
function norm(v) { return JSON.stringify(v); }
(async () => {
  if (typeof fn !== "function") { console.error("HARNESS_ERROR: export ${exportName} is not a function"); process.exit(2); }
  let diverged = 0;
  for (let i = 0; i < cases.length; i++) {
    const c = cases[i];
    let got;
    try { got = await fn.apply(null, c.input); }
    catch (e) { console.error("HARNESS_ERROR case " + i + ": threw " + (e && e.message)); process.exit(2); }
    if (norm(got) !== norm(c.output)) {
      diverged++;
      console.log("DIVERGE case " + i + ": input=" + norm(c.input) + " expected=" + norm(c.output) + " got=" + norm(got));
    }
  }
  if (diverged > 0) { console.log("DIFFERENTIAL: " + diverged + "/" + cases.length + " diverged"); process.exit(1); }
  console.log("DIFFERENTIAL: all " + cases.length + " match");
  process.exit(0);
})();
`;
}

// The same contract in Python. The golden table is embedded as a JSON STRING and
// json.loads'd (so JS true/false/null become valid Python values). No deps beyond
// the stdlib — python:3-alpine suffices in the hardened container.
function renderPyHarness(entryFile: string, exportName: string, cases: DiffParams["cases"]): string {
  const casesJson = JSON.stringify(JSON.stringify(cases));
  return `import json, sys, importlib.util
# GENERATED by @brainblast/core differential oracle (python). Runs ONLY the candidate.
spec = importlib.util.spec_from_file_location("candidate", ${JSON.stringify(entryFile)})
mod = importlib.util.module_from_spec(spec)
try:
    spec.loader.exec_module(mod)
except Exception as e:
    print("HARNESS_ERROR: " + str(e), file=sys.stderr); sys.exit(2)
fn = getattr(mod, ${JSON.stringify(exportName)}, None)
if not callable(fn):
    print("HARNESS_ERROR: export ${exportName} is not callable", file=sys.stderr); sys.exit(2)
cases = json.loads(${casesJson})
def norm(v): return json.dumps(v, sort_keys=True)
diverged = 0
for i, c in enumerate(cases):
    try:
        got = fn(*c["input"])
    except Exception as e:
        print("HARNESS_ERROR case %d: %s" % (i, e), file=sys.stderr); sys.exit(2)
    if norm(got) != norm(c["output"]):
        diverged += 1
        print("DIVERGE case %d: input=%s expected=%s got=%s" % (i, norm(c["input"]), norm(c["output"]), norm(got)))
if diverged > 0:
    print("DIFFERENTIAL: %d/%d diverged" % (diverged, len(cases))); sys.exit(1)
print("DIFFERENTIAL: all %d match" % len(cases)); sys.exit(0)
`;
}

const tsRunner: LangRunner = {
  ext: /\.(ts|tsx|mts|cts|js|mjs|cjs)$/,
  prepare(sandbox, copied, entryFile) {
    // Transpile every TS file → a sibling CommonJS .js on the host; run plain node.
    for (const f of copied) {
      if (!TS_EXT.test(f)) continue;
      writeFileSync(f.replace(TS_EXT, ".js"), transpileToCjs(readFileSync(f, "utf8")));
    }
    writeFileSync(join(sandbox, "package.json"), '{"type":"commonjs"}\n');
    return "./" + entryFile.replace(TS_EXT, "").replace(/\.(js|mjs|cjs)$/, "");
  },
  harnessFile: "_diff_harness.cjs",
  renderHarness: renderNodeHarness,
  command: "node",
  image: "node:22-alpine",
  defaultEntry: "index.ts",
};

const pyRunner: LangRunner = {
  ext: /\.py$/,
  prepare(_sandbox, _copied, entryFile) {
    return entryFile; // no transpile — the harness loads the .py by path
  },
  harnessFile: "_diff_harness.py",
  renderHarness: renderPyHarness,
  command: "python3",
  image: "python:3.12-alpine",
  defaultEntry: "index.py",
};

const RUNNERS: Record<string, LangRunner> = {
  typescript: tsRunner,
  javascript: tsRunner,
  python: pyRunner,
};

export const differentialBackend: OracleBackend = {
  method: "differential",
  tier: 2,
  supports,
  async verify({ dir, rule, context = "local" }: OracleTarget): Promise<OracleVerdict> {
    const t0 = Date.now();
    const p = (rule.check?.params ?? {}) as DiffParams;
    if (!supports(rule)) {
      return unknown("rule is missing/invalid differential-io params (export identifier + cases[])", t0);
    }
    const runner = RUNNERS[p.lang ?? "typescript"];
    const entryFile = p.entryFile ?? runner.defaultEntry;
    const sandbox = makeSandboxDir(".oracle-diff-");
    try {
      // Copy the candidate (files matching the runner's ext), let the runner prepare
      // it (e.g. transpile TS → CJS; Python copies as-is), and write the harness. The
      // candidate must be self-contained (golden-I/O is pure logic); a missing dep
      // surfaces as a harness error → UNKNOWN, never a false RED.
      const copied = copyCandidate(dir, sandbox, runner.ext);
      if (copied.length === 0) return unknown(`no ${p.lang ?? "typescript"} candidate files under ${dir}`, t0);
      const entrySpec = runner.prepare(sandbox, copied, entryFile);
      writeFileSync(join(sandbox, runner.harnessFile), runner.renderHarness(entrySpec, p.export!, p.cases));

      // LOCAL and INGEST run the SAME per-language command — isolation is chosen by
      // runInSandbox from context. The hardened container ships only the interpreter.
      const res = runInSandbox({
        dir: sandbox,
        command: runner.command,
        args: [runner.harnessFile],
        image: runner.image,
        context,
        timeoutMs: p.timeoutMs ?? 30_000,
      });

      if (res.status === "refused") {
        return { color: "UNKNOWN", method: "differential", detail: res.detail ?? "ingest sandbox refused", durationMs: Date.now() - t0 };
      }
      if (res.status !== "ok") {
        return { color: "UNKNOWN", method: "differential", detail: `candidate did not run cleanly (${res.status}): ${res.detail ?? res.stderr.split("\n")[0]}`, durationMs: Date.now() - t0 };
      }
      // exit 0 = matches golden (GREEN); 1 = diverged (RED); else UNKNOWN.
      if (res.exitCode === 0) {
        return { color: "GREEN", method: "differential", detail: `matches the golden I/O table (${p.cases!.length} case(s)).`, evidence: { cases: p.cases!.length, isolation: res.isolation }, durationMs: Date.now() - t0 };
      }
      if (res.exitCode === 1) {
        const firstDiverge = res.stdout.split("\n").find((l) => l.startsWith("DIVERGE")) ?? "output diverges from the golden table";
        return { color: "RED", method: "differential", detail: `diverges from the golden I/O table — ${firstDiverge}`, evidence: { cases: p.cases!.length, isolation: res.isolation, diff: firstDiverge }, durationMs: Date.now() - t0 };
      }
      const harnessErr = [...res.stderr.split("\n"), ...res.stdout.split("\n")].find((l) => l.includes("HARNESS_ERROR"));
      return { color: "UNKNOWN", method: "differential", detail: `harness error: ${harnessErr ?? res.stderr.split("\n")[0] ?? "exit " + res.exitCode}`, durationMs: Date.now() - t0 };
    } catch (e: any) {
      return unknown(`differential oracle could not run: ${e?.message ?? String(e)}`, t0);
    } finally {
      rmSync(sandbox, { recursive: true, force: true });
    }
  },
};

function unknown(detail: string, t0: number): OracleVerdict {
  return { color: "UNKNOWN", method: "differential", detail, durationMs: Date.now() - t0 };
}
