import { writeFileSync, rmSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { ts } from "ts-morph";
import { runInSandbox, makeSandboxDir, copyCandidate } from "../sandbox.ts";
import type { OracleBackend, OracleVerdict, OracleTarget } from "../types.ts";
import type { Rule } from "../../types.ts";

// Tier 2 — the REFERENCE oracle: run the candidate against a recorded golden I/O
// table on the same inputs; RED if outputs diverge, GREEN if they match. This
// grades "is this the SAME AS correct" — off-by-one, wrong rounding, a wrong
// constant — the long tail of "looks right, computes wrong" where static rules are
// weakest (`wrong-constant`, scaling/serialization bugs).
//
// HOW IT RUNS IN A SANDBOX, PORTABLY (v0.9.2): the candidate is TypeScript, but we
// must NOT need a TS runtime (tsx/esbuild) or any node_modules INSIDE the sandbox —
// native binaries can't cross darwin↔linux / musl↔glibc, which is what broke the
// first container attempt. So we transpile the candidate + harness TS → plain
// CommonJS JS ON THE HOST (using the TypeScript compiler we already bundle via
// ts-morph — compilation, never execution), then run plain `node harness.cjs`. A
// golden-I/O candidate is pure logic with no runtime deps, so node alone suffices.
// The result: the LOCAL light isolate and the INGEST hardened container run the
// IDENTICAL command (`node harness.cjs`) — only the isolation differs — so the
// whole harness/exit-code path is locally testable and the container "just works"
// (node:22-alpine ships node; nothing else is needed).
//
// Honesty guard: the golden table is VETTED and owned — a contributor supplies
// candidate code and *claimed* behavior, never the oracle of truth itself.
//
// Rule binding (check.kind: "differential-io"):
//   params: {
//     entryFile: "lamports.ts",     // candidate file to import (relative to fixture dir)
//     export:    "solToLamports",   // the function under test
//     cases: [ { input: [1], output: 1000000000 }, … ]  // the golden table
//   }

interface DiffParams {
  entryFile?: string;
  export?: string;
  cases?: Array<{ input: unknown[]; output: unknown }>;
  /** Optional wall-clock budget for the candidate run (default 30s). */
  timeoutMs?: number;
}

const JS_IDENTIFIER = /^[A-Za-z_$][\w$]*$/;
const TS_EXT = /\.(ts|tsx|mts|cts)$/;

function supports(rule: Rule): boolean {
  if (rule.check?.kind !== "differential-io") return false;
  const p = (rule.check?.params ?? {}) as DiffParams;
  return Array.isArray(p.cases) && p.cases.length > 0 && !!p.export && JS_IDENTIFIER.test(p.export);
}

// Transpile a single TS source to CommonJS JS (type-strip + ESM→CJS). No type
// check, no bundling, no native deps — pure string→string.
function transpileToCjs(src: string): string {
  return ts.transpileModule(src, {
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2022,
      esModuleInterop: true,
      removeComments: false,
    },
  }).outputText;
}

// A self-contained CommonJS harness: require the candidate, run each golden case,
// exit 0 (all match → GREEN), 1 (any divergence → RED), or 2 (harness error →
// UNKNOWN). Deep-equal via stable JSON. Plain node — no deps.
function renderHarness(entryRequire: string, exportName: string, cases: DiffParams["cases"]): string {
  return `"use strict";
// GENERATED by @brainblast/core differential oracle. Runs ONLY the candidate.
const mod = require(${JSON.stringify(entryRequire)});
const fn = mod[${JSON.stringify(exportName)}] || (mod.default && mod.default[${JSON.stringify(exportName)}]) || mod.default;
const cases = ${JSON.stringify(cases)};
function norm(v) { return JSON.stringify(v); }
(async () => {
  if (typeof fn !== "function") { console.error("HARNESS_ERROR: export ${exportName} is not a function"); process.exit(2); }
  let diverged = 0;
  for (let i = 0; i < cases.length; i++) {
    const c = cases[i];
    let got;
    try { got = await fn.apply(null, c.input); }
    catch (e) { console.error("HARNESS_ERROR case " + i + ": threw " + (e && e.message)); process.exit(2); }
    if (norm(got) !== norm(c.output)) {
      diverged++;
      console.log("DIVERGE case " + i + ": input=" + norm(c.input) + " expected=" + norm(c.output) + " got=" + norm(got));
    }
  }
  if (diverged > 0) { console.log("DIFFERENTIAL: " + diverged + "/" + cases.length + " diverged"); process.exit(1); }
  console.log("DIFFERENTIAL: all " + cases.length + " match");
  process.exit(0);
})();
`;
}

export const differentialBackend: OracleBackend = {
  method: "differential",
  tier: 2,
  supports,
  async verify({ dir, rule, context = "local" }: OracleTarget): Promise<OracleVerdict> {
    const t0 = Date.now();
    const p = (rule.check?.params ?? {}) as DiffParams;
    if (!supports(rule)) {
      return unknown("rule is missing/invalid differential-io params (export identifier + cases[])", t0);
    }
    const entryFile = p.entryFile ?? "index.ts";
    const sandbox = makeSandboxDir(".oracle-diff-");
    try {
      // Copy the candidate, then transpile every TS file → a sibling .js (CommonJS).
      // The candidate must be self-contained (golden-I/O is pure logic); any import
      // of a missing dep surfaces as a harness error → UNKNOWN, never a false RED.
      const copied = copyCandidate(dir, sandbox);
      if (copied.length === 0) return unknown(`no candidate files under ${dir}`, t0);
      for (const f of copied) {
        if (!TS_EXT.test(f)) continue;
        const jsPath = f.replace(TS_EXT, ".js");
        writeFileSync(jsPath, transpileToCjs(readFileSync(f, "utf8")));
      }
      // The transpiled output is CommonJS. The sandbox lives under packages/core
      // (which is "type":"module"), and the container's /work is type-less — either
      // way, force CommonJS for the sandbox's .js so `require("./entry")` works.
      writeFileSync(join(sandbox, "package.json"), '{"type":"commonjs"}\n');

      const entryRequire = "./" + entryFile.replace(TS_EXT, "").replace(/\.(js|mjs|cjs)$/, "");
      writeFileSync(join(sandbox, "_diff_harness.cjs"), renderHarness(entryRequire, p.export!, p.cases));

      // LOCAL and INGEST run the SAME command — plain node on transpiled JS. No
      // tsx, no node_modules, no native deps: the hardened container (node:22-alpine)
      // needs nothing but `node`. Isolation is chosen by runInSandbox from context.
      const res = runInSandbox({
        dir: sandbox,
        command: "node",
        args: ["_diff_harness.cjs"],
        context,
        timeoutMs: p.timeoutMs ?? 30_000,
      });

      if (res.status === "refused") {
        return { color: "UNKNOWN", method: "differential", detail: res.detail ?? "ingest sandbox refused", durationMs: Date.now() - t0 };
      }
      if (res.status !== "ok") {
        return { color: "UNKNOWN", method: "differential", detail: `candidate did not run cleanly (${res.status}): ${res.detail ?? res.stderr.split("\n")[0]}`, durationMs: Date.now() - t0 };
      }
      // exit 0 = matches golden (GREEN); 1 = diverged (RED); else UNKNOWN.
      if (res.exitCode === 0) {
        return { color: "GREEN", method: "differential", detail: `matches the golden I/O table (${p.cases!.length} case(s)).`, evidence: { cases: p.cases!.length, isolation: res.isolation }, durationMs: Date.now() - t0 };
      }
      if (res.exitCode === 1) {
        const firstDiverge = res.stdout.split("\n").find((l) => l.startsWith("DIVERGE")) ?? "output diverges from the golden table";
        return { color: "RED", method: "differential", detail: `diverges from the golden I/O table — ${firstDiverge}`, evidence: { cases: p.cases!.length, isolation: res.isolation, diff: firstDiverge }, durationMs: Date.now() - t0 };
      }
      const harnessErr = [...res.stderr.split("\n"), ...res.stdout.split("\n")].find((l) => l.includes("HARNESS_ERROR"));
      return { color: "UNKNOWN", method: "differential", detail: `harness error: ${harnessErr ?? res.stderr.split("\n")[0] ?? "exit " + res.exitCode}`, durationMs: Date.now() - t0 };
    } catch (e: any) {
      return unknown(`differential oracle could not run: ${e?.message ?? String(e)}`, t0);
    } finally {
      rmSync(sandbox, { recursive: true, force: true });
    }
  },
};

function unknown(detail: string, t0: number): OracleVerdict {
  return { color: "UNKNOWN", method: "differential", detail, durationMs: Date.now() - t0 };
}
