#!/usr/bin/env python3
"""Parse brainblast report.json and emit GitHub Actions outputs.

Outputs (written to GITHUB_OUTPUT format):
  verdict      — ready | caution | blocked
  risk_totals  — JSON string
  should_fail  — true | false
  comment_body — formatted PR comment (markdown)
"""

import json
import sys

SEVERITY_ORDER = ["critical", "high", "medium", "low"]
SEVERITY_EMOJI = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🔵",
}
VERDICT_EMOJI = {"ready": "✅", "caution": "⚠️", "blocked": "🚫"}


def should_fail(totals: dict, threshold: str) -> bool:
    if threshold == "never":
        return False
    for sev in SEVERITY_ORDER:
        if totals.get(sev, 0) > 0:
            return True
        if sev == threshold:
            break
    return False


def main() -> None:
    if len(sys.argv) < 3:
        print("usage: parse-report.py <report.json> <fail-on>", file=sys.stderr)
        sys.exit(2)

    report_path, fail_on = sys.argv[1], sys.argv[2]

    try:
        with open(report_path) as f:
            report = json.load(f)
    except (OSError, json.JSONDecodeError) as e:
        print(f"error: could not read {report_path}: {e}", file=sys.stderr)
        sys.exit(1)

    summary = report.get("summary", {})
    verdict = summary.get("verdict", "unknown")
    totals = report.get("riskTotals", {})
    components = report.get("components", [])
    checks = report.get("checks", [])

    fail = should_fail(totals, fail_on)

    # ── Build heatmap table ──────────────────────────────────────────────────
    total_risks = sum(totals.get(s, 0) for s in SEVERITY_ORDER)
    heatmap_rows = " | ".join(
        f"{SEVERITY_EMOJI[s]} **{totals.get(s, 0)}** {s}" for s in SEVERITY_ORDER
    )

    # ── Top risks across all components ──────────────────────────────────────
    all_risks = []
    for comp in components:
        for risk in comp.get("risks", []):
            all_risks.append((risk.get("severity", "low"), comp.get("name", "?"), risk))
    all_risks.sort(key=lambda x: SEVERITY_ORDER.index(x[0]) if x[0] in SEVERITY_ORDER else 99)

    top_risks_md = ""
    if all_risks:
        rows = []
        for sev, comp_name, risk in all_risks[:8]:
            adv = f" ([{risk.get('advisoryId','')}]({risk.get('advisoryUrl','')}))" if risk.get("advisoryId") else ""
            rows.append(f"| {SEVERITY_EMOJI[sev]} {sev} | `{comp_name}` | {risk.get('title','')}{adv} |")
        top_risks_md = (
            "\n\n**Top risks**\n\n"
            "| Severity | Component | Risk |\n"
            "|---|---|---|\n"
            + "\n".join(rows)
        )

    # ── Deterministic checks summary ─────────────────────────────────────────
    check_totals = report.get("checkTotals", {})
    checks_md = ""
    if check_totals:
        fails = check_totals.get("fail", 0)
        passes = check_totals.get("pass", 0)
        cant = check_totals.get("cant_tell", 0)
        checks_md = (
            f"\n\n**Static audit** — {passes} pass / {fails} fail / {cant} cant_tell"
        )
        failing = [c for c in checks if c.get("result") == "fail"]
        if failing:
            check_rows = "\n".join(
                f"| `{c.get('ruleId','')}` | `{c.get('file','')}:{c.get('line','')}` | {c.get('title','')} |"
                for c in failing[:5]
            )
            checks_md += (
                "\n\n| Rule | Location | Finding |\n|---|---|---|\n" + check_rows
            )
            if len(failing) > 5:
                checks_md += f"\n| … | | +{len(failing)-5} more — see report.json |"

    # ── Assemble comment ──────────────────────────────────────────────────────
    verdict_label = VERDICT_EMOJI.get(verdict, "❓") + " " + verdict.upper()
    building = summary.get("building", "")
    building_line = f"\n> {building}" if building else ""

    comment = (
        f"<!-- brainblast-audit -->\n"
        f"## 🧠 brainblast audit — {verdict_label}\n"
        f"{building_line}\n\n"
        f"| {heatmap_rows} |\n"
        f"|{'|'.join(['---']*4)}|\n"
        f"{top_risks_md}"
        f"{checks_md}\n\n"
        f"<details><summary>Report details</summary>\n\n"
        f"- **Components researched:** {len(components)}\n"
        f"- **Total risks:** {total_risks}\n"
    )
    top_risk = summary.get("topRisk")
    if top_risk:
        comment += f"- **Top risk:** {top_risk}\n"
    must_decide = summary.get("mustDecideFirst")
    if must_decide:
        comment += f"- **Must decide first:** {must_decide}\n"
    comment += f"\n</details>\n\n*Generated by [brainblast](https://github.com/DSB-117/brainblast)*"

    # ── Emit outputs ──────────────────────────────────────────────────────────
    risk_totals_json = json.dumps(totals)
    # Escape newlines for GITHUB_OUTPUT multiline value
    escaped_comment = comment.replace("%", "%25").replace("\n", "%0A").replace("\r", "%0D")

    print(f"verdict={verdict}")
    print(f"risk_totals={risk_totals_json}")
    print(f"should_fail={'true' if fail else 'false'}")
    print(f"comment_body={escaped_comment}")


if __name__ == "__main__":
    main()
