import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

// Generates the DURABLE artifact: a behavioral contract test that forges a
// Stripe webhook and asserts the handler rejects it. This is the moat, not a
// re-run of the static check. Red until the handler verifies on the raw body.
export interface GenerateOpts {
  handlerImportPath: string; // resolvable module specifier (abs path ok under vitest)
  handlerExport: string;
  outPath: string;
}

export function generateBehavioralTest(opts: GenerateOpts): string {
  const src = `// GENERATED by brainblast-spike (T1). The durable guardrail.
// This test goes RED until the Stripe webhook verifies signatures on the RAW body.
// Delete it and the gate re-fails on the next run.
import { describe, it, expect, beforeAll } from "vitest";
import Stripe from "stripe";
import { ${opts.handlerExport} } from ${JSON.stringify(opts.handlerImportPath)};

const SECRET = "whsec_brainblast_test_secret";
const stripe = new Stripe("sk_test_brainblast");
const payload = JSON.stringify({
  id: "evt_1",
  type: "payment_intent.succeeded",
  data: { object: { id: "pi_1" } },
});

beforeAll(() => {
  process.env.STRIPE_WEBHOOK_SECRET = SECRET;
  process.env.STRIPE_SECRET_KEY = "sk_test_brainblast";
});

describe("Stripe webhook signature verification (brainblast contract)", () => {
  it("accepts a validly-signed event", () => {
    const sig = stripe.webhooks.generateTestHeaderString({ payload, secret: SECRET });
    expect(() => ${opts.handlerExport}(payload, sig)).not.toThrow();
  });

  it("REJECTS an invalid signature (forged event)", () => {
    expect(() => ${opts.handlerExport}(payload, "t=1,v1=deadbeef")).toThrow();
  });

  it("REJECTS a mutated body under a valid-looking signature", () => {
    const sig = stripe.webhooks.generateTestHeaderString({ payload, secret: SECRET });
    const mutated = payload.replace("succeeded", "failed");
    expect(() => ${opts.handlerExport}(mutated, sig)).toThrow();
  });
});
`;
  mkdirSync(dirname(opts.outPath), { recursive: true });
  writeFileSync(opts.outPath, src);
  return opts.outPath;
}
