import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

// Generates the durable artifact: a behavioral contract test that mints real
// ES256 tokens (mirroring Privy access tokens) and asserts the verifier rejects
// a bad signature, a wrong audience, and a wrong issuer. Behavioral, not a
// re-run of the static check.
export interface GenerateOpts {
  handlerImportPath: string;
  handlerExport: string;
  outPath: string;
}

export function generateBehavioralTest(opts: GenerateOpts): string {
  const src = `// GENERATED by brainblast-spike (T2). The durable guardrail.
// Goes RED until the Privy access token is verified (signature + aud + iss).
import { describe, it, expect, beforeAll } from "vitest";
import { SignJWT, generateKeyPair, exportSPKI } from "jose";
import { ${opts.handlerExport} } from ${JSON.stringify(opts.handlerImportPath)};

const APP_ID = "app_brainblast";
let valid = "", badSignature = "", wrongAudience = "", wrongIssuer = "";

beforeAll(async () => {
  const { publicKey, privateKey } = await generateKeyPair("ES256");
  const attacker = await generateKeyPair("ES256");
  process.env.PRIVY_APP_ID = APP_ID;
  process.env.PRIVY_VERIFICATION_KEY = await exportSPKI(publicKey);

  const mint = (signer: any, iss: string, aud: string) =>
    new SignJWT({})
      .setProtectedHeader({ alg: "ES256" })
      .setIssuer(iss)
      .setAudience(aud)
      .setSubject("did:privy:user_1")
      .setExpirationTime("1h")
      .sign(signer);

  valid = await mint(privateKey, "privy.io", APP_ID);
  badSignature = await mint(attacker.privateKey, "privy.io", APP_ID);
  wrongAudience = await mint(privateKey, "privy.io", "app_evil");
  wrongIssuer = await mint(privateKey, "evil.com", APP_ID);
});

// Wrap so a sync throw and an async reject look the same to the assertions.
const call = (t: string) => Promise.resolve().then(() => ${opts.handlerExport}(t));

describe("Privy access-token verification (brainblast contract)", () => {
  it("accepts a valid token", async () => {
    await expect(call(valid)).resolves.toBeDefined();
  });
  it("REJECTS a bad signature (forged token)", async () => {
    await expect(call(badSignature)).rejects.toThrow();
  });
  it("REJECTS a wrong audience (token from another app)", async () => {
    await expect(call(wrongAudience)).rejects.toThrow();
  });
  it("REJECTS a wrong issuer", async () => {
    await expect(call(wrongIssuer)).rejects.toThrow();
  });
});
`;
  mkdirSync(dirname(opts.outPath), { recursive: true });
  writeFileSync(opts.outPath, src);
  return opts.outPath;
}
