import type { TestTemplate } from "../types.ts";

// Vetted behavioral-contract template for Anchor program traps.
//
// Unlike TypeScript templates (which generate Vitest files), Anchor traps
// require a running Solana program. This template generates a Rust test module
// using Anchor's built-in test framework (anchor test / cargo test-bpf).
//
// The generated test does NOT run in the brainblast Vitest suite — it lives
// alongside the target program's existing test suite. When synth-prove
// evaluates the proof-as-classifier loop for Anchor rules, the GREEN/RED
// determination comes from the static checker (tree-sitter-rust), not from
// executing this template.
//
// Usage after promotion:
//   1. Copy the generated test into your program's `tests/` directory.
//   2. Run: anchor test  (or cargo test-bpf for native programs)
//   3. Both test cases must pass (second invocation rejected).
export const anchorProgramTest: TestTemplate = ({ handlerImportPath, handlerExport }) =>
  `// GENERATED by @brainblast/core. Durable guardrail — paste into your
// Anchor program's tests/ directory and run: anchor test
//
// Handler under test: ${handlerExport} (${handlerImportPath})
//
// Contract: calling the instruction a second time on the same account must
// fail with an AlreadyInitialized error (or equivalent). If it succeeds,
// the account state has been silently overwritten.

use anchor_lang::prelude::*;
use anchor_lang::solana_program::instruction::InstructionError;

// NOTE: Replace MyProgram with your program's generated client and adjust
// the instruction call to match your handler's signature.

#[cfg(test)]
mod brainblast_reinit_guard_test {
    // Import your program's client — e.g.:
    //   use my_program::*;
    //   use anchor_lang::solana_program::pubkey::Pubkey;

    #[tokio::test]
    async fn first_call_succeeds() {
        // Arrange: set up a fresh program test environment
        // let program_test = ProgramTest::new("${handlerExport}", id(), None);
        // let (mut banks_client, payer, recent_blockhash) = program_test.start().await;

        // Act: invoke ${handlerExport} for the first time
        // assert!(result.is_ok(), "First initialization must succeed");
        todo!("implement: first call to ${handlerExport} should succeed");
    }

    #[tokio::test]
    async fn second_call_is_rejected() {
        // Arrange: initialize the account (same as above)
        // Act: invoke ${handlerExport} a SECOND time on the same account
        // Assert: must fail — AlreadyInitialized or similar
        // let err = result.unwrap_err();
        // assert!(matches!(err, ...AlreadyInitialized));
        todo!("implement: second call to ${handlerExport} must be rejected");
    }
}
`;
