import type { TestTemplate } from "../types.ts";

// Vetted behavioral-contract template for the Bags fee-share creator-inclusion
// trap. The Bags API is mainnet-only (no devnet), so the contract is asserted
// against the config the builder hands to the SDK — the SDK call is mocked to
// capture its argument, and we assert on the captured feeClaimers. No network.
export const bagsFeeShare: TestTemplate = ({ handlerImportPath, handlerExport }) => `// GENERATED by @brainblast/core. Durable guardrail — RED until the fee-share
// config includes the creator wallet with a non-zero userBps summing to 10000.
import { describe, it, expect, vi, beforeEach } from "vitest";

let captured: any;
vi.mock("@bagsfm/bags-sdk", () => ({
  createBagsFeeShareConfig: (cfg: any) => {
    captured = cfg;
    return { meteoraConfigKey: "mock-config-key" };
  },
  BagsSDK: class {},
}));

import { ${handlerExport} } from ${JSON.stringify(handlerImportPath)};

const CREATOR = "CreatorWa11etPubKey1111111111111111111111111";

describe("Bags fee-share creator inclusion (brainblast contract)", () => {
  beforeEach(() => {
    captured = undefined;
  });

  it("passes the creator wallet into feeClaimers", () => {
    ${handlerExport}(CREATOR);
    const claimers = captured?.feeClaimers ?? [];
    expect(claimers.some((c: any) => c.user === CREATOR)).toBe(true);
  });

  it("allocates the creator a non-zero userBps", () => {
    ${handlerExport}(CREATOR);
    const entry = (captured?.feeClaimers ?? []).find((c: any) => c.user === CREATOR);
    expect(entry?.userBps ?? 0).toBeGreaterThan(0);
  });

  it("feeClaimers userBps sum to exactly 10000", () => {
    ${handlerExport}(CREATOR);
    const sum = (captured?.feeClaimers ?? []).reduce((s: number, c: any) => s + c.userBps, 0);
    expect(sum).toBe(10000);
  });
});
`;
