import type { TestTemplate } from "../types.ts";

// Vetted behavioral-contract template for the Metaplex metadata immutability trap.
//
// The trap: a project creating on-chain token metadata via Metaplex's createV1
// (or createNft / createAndMint) omits `isMutable: false` — so the metadata
// defaults to mutable. Anyone with the update authority can later change the
// token name, symbol, or URI. For tokens where immutability is a trust property
// (stablecoins, governance tokens, NFTs with locked traits) this is a silent
// risk: the on-chain record looks fine at launch, but the authority key becomes
// a permanent attack surface.
//
// We mock @metaplex-foundation/mpl-token-metadata's `createV1` to capture the
// options object passed by the handler, then assert isMutable === false.
// No network or validator required.
export const metaplexImmutableMetadata: TestTemplate = ({ handlerImportPath, handlerExport }) =>
  `// GENERATED by @brainblast/core. Durable guardrail — RED until the metadata
// creation call includes isMutable: false.
import { describe, it, expect, vi, beforeEach } from "vitest";

// Capture target — vi.hoisted ensures this is initialized before vi.mock factories run.
const captured = vi.hoisted(() => ({ value: { isMutable: undefined as boolean | undefined } }));

vi.mock("@metaplex-foundation/mpl-token-metadata", () => ({
  createV1: (_umi: any, opts: any) => {
    captured.value.isMutable = opts.isMutable;
    return Promise.resolve();
  },
  createNft: (_metaplex: any, opts: any) => {
    captured.value.isMutable = opts.isMutable;
    return Promise.resolve({ nft: {} });
  },
  createAndMint: (_umi: any, opts: any) => {
    captured.value.isMutable = opts.isMutable;
    return Promise.resolve();
  },
  // Stub enums so import-only references don't crash
  TokenStandard: { Fungible: 2, FungibleAsset: 3, NonFungible: 0, NonFungibleEdition: 1 },
  printSupply: (x: any) => x,
  percentAmount: (n: number) => n,
}));

import { ${handlerExport} } from ${JSON.stringify(handlerImportPath)};

describe("Metaplex metadata immutability (brainblast contract)", () => {
  beforeEach(() => {
    captured.value.isMutable = undefined;
  });

  it("passes isMutable: false to the metadata creation call", async () => {
    await Promise.resolve(${handlerExport}({} as any));
    expect(
      captured.value.isMutable,
      "createV1/createNft/createAndMint was not called or isMutable was not passed",
    ).toBeDefined();
    expect(captured.value.isMutable).toBe(false);
  });

  it("does not leave metadata mutable (isMutable !== true)", async () => {
    await Promise.resolve(${handlerExport}({} as any));
    expect(captured.value.isMutable).not.toBe(true);
  });
});
`;
