import type { TestTemplate } from "../types.ts";

// Vetted behavioral-contract template for Stripe webhook signature verification.
export const stripeWebhookSignature: TestTemplate = ({ handlerImportPath, handlerExport }) => `// GENERATED by @brainblast/core. Durable guardrail — RED until the webhook
// verifies the signature on the RAW body.
import { describe, it, expect, beforeAll } from "vitest";
import Stripe from "stripe";
import { ${handlerExport} } from ${JSON.stringify(handlerImportPath)};

const SECRET = "whsec_brainblast_test_secret";
const stripe = new Stripe("sk_test_brainblast");
const payload = JSON.stringify({ id: "evt_1", type: "payment_intent.succeeded", data: { object: { id: "pi_1" } } });

beforeAll(() => {
  process.env.STRIPE_WEBHOOK_SECRET = SECRET;
  process.env.STRIPE_SECRET_KEY = "sk_test_brainblast";
});

describe("Stripe webhook signature verification (brainblast contract)", () => {
  it("accepts a validly-signed event", () => {
    const sig = stripe.webhooks.generateTestHeaderString({ payload, secret: SECRET });
    expect(() => ${handlerExport}(payload, sig)).not.toThrow();
  });
  it("REJECTS an invalid signature (forged event)", () => {
    expect(() => ${handlerExport}(payload, "t=1,v1=deadbeef")).toThrow();
  });
  it("REJECTS a mutated body under a valid-looking signature", () => {
    const sig = stripe.webhooks.generateTestHeaderString({ payload, secret: SECRET });
    const mutated = payload.replace("succeeded", "failed");
    expect(() => ${handlerExport}(mutated, sig)).toThrow();
  });
});
`;
