import type { TestTemplate } from "../types.ts";

// Vetted behavioral-contract template for the Token-2022 vs legacy Token
// program-ID pinning trap.
//
// The trap: a project that wants Token-2022 mints (imports
// TOKEN_2022_PROGRAM_ID) calls `createMint` and forgets to pass it as the
// programId argument — so the SDK silently defaults to the LEGACY token
// program. The mint exists, looks fine in explorers, and is uninstantiable
// for Token-2022 features (transfer hooks, transfer fees, confidential
// transfers). There is no on-chain fix; the mint's owner program is part of
// its identity.
//
// We mock @solana/spl-token's `createMint` so the test runs offline and we
// can capture the programId argument the handler actually passed. No
// network, no validator, no compromise on determinism.
export const tokenProgramConsistency: TestTemplate = ({ handlerImportPath, handlerExport }) => `// GENERATED by @brainblast/core. Durable guardrail — RED until createMint is
// called with TOKEN_2022_PROGRAM_ID as the programId argument.
import { describe, it, expect, vi, beforeEach } from "vitest";
import { PublicKey } from "@solana/web3.js";

// Keep the well-known token program addresses as strings; we compare via
// .toString() so we never depend on PublicKey identity across the mock
// boundary. Defined at module scope (not used inside vi.mock factory, which
// is hoisted before any const initializations).
const TOKEN_PROGRAM_ID_STR = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA";
const TOKEN_2022_PROGRAM_ID_STR = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb";

// The capture target. vi.hoisted runs before vi.mock factory hoisting, so the
// factory below can close over \`captured\` safely.
const captured = vi.hoisted(() => ({ value: { programId: undefined as any } }));

vi.mock("@solana/spl-token", () => {
  // PublicKey instantiation lives INSIDE the factory so it runs after the
  // import from @solana/web3.js has resolved.
  const { PublicKey: PK } = require("@solana/web3.js");
  const TOKEN_PROGRAM_ID = new PK("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA");
  const TOKEN_2022_PROGRAM_ID = new PK("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb");
  const FAKE_MINT = new PK("11111111111111111111111111111111");
  return {
    TOKEN_PROGRAM_ID,
    TOKEN_2022_PROGRAM_ID,
    createMint: (
      _connection: any,
      _payer: any,
      _mintAuthority: any,
      _freezeAuthority: any,
      _decimals: any,
      _keypair: any,
      _confirmOptions: any,
      programId: any,
    ) => {
      captured.value.programId = programId;
      return Promise.resolve(FAKE_MINT);
    },
  };
});

import { ${handlerExport} } from ${JSON.stringify(handlerImportPath)};

describe("Token-2022 program-ID pinning (brainblast contract)", () => {
  beforeEach(() => {
    captured.value.programId = undefined;
  });

  it("passes TOKEN_2022_PROGRAM_ID as the createMint programId argument", async () => {
    await Promise.resolve(${handlerExport}({} as any));
    expect(captured.value.programId, "createMint was not called or did not receive a programId").toBeDefined();
    expect(String(captured.value.programId)).toBe(TOKEN_2022_PROGRAM_ID_STR);
  });

  it("does not default to the legacy token program", async () => {
    await Promise.resolve(${handlerExport}({} as any));
    expect(String(captured.value.programId)).not.toBe(TOKEN_PROGRAM_ID_STR);
  });
});
`;
